"""init

Revision ID: b3d7afa09adb
Revises: 
Create Date: 2025-12-14 17:24:30.262721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b3d7afa09adb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatthread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatthread', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatthread_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatthread_external_thread_id'), ['external_thread_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_chatthread_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatthread_updated_at'), ['updated_at'], unique=False)

    op.create_table('integrationcredential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('encrypted_secret', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integrationcredential', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrationcredential_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrationcredential_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrationcredential_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrationcredential_updated_at'), ['updated_at'], unique=False)

    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_project_updated_at'), ['updated_at'], unique=False)

    op.create_table('repository',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_analyzed', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repository_url'), ['url'], unique=True)

    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('source_platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('story_points', sa.Integer(), nullable=False),
    sa.Column('files_changed_count', sa.Integer(), nullable=False),
    sa.Column('status_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_source_platform'), ['source_platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_type'), ['type'], unique=False)

    op.create_table('analysisreport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('developer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=False),
    sa.Column('prs_merged', sa.Integer(), nullable=False),
    sa.Column('commits_count', sa.Integer(), nullable=False),
    sa.Column('security_alerts', sa.Boolean(), nullable=False),
    sa.Column('detected_skills', sa.JSON(), nullable=True),
    sa.Column('feedback_summary', sa.Text(), nullable=True),
    sa.Column('linear_ticket_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_thread_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['chat_thread_id'], ['chatthread.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatmessage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatmessage_chat_thread_id'), ['chat_thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatmessage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatmessage_role'), ['role'], unique=False)

    op.create_table('projectintegration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['integrationcredential.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projectintegration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projectintegration_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_projectintegration_credential_id'), ['credential_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projectintegration_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projectintegration_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_projectintegration_updated_at'), ['updated_at'], unique=False)

    op.create_table('projectrepository',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'repository_id')
    )
    with op.batch_alter_table('projectrepository', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projectrepository_created_at'), ['created_at'], unique=False)

    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source_platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('story_points', sa.Integer(), nullable=False),
    sa.Column('status_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_source_id'), ['source_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_ticket_source_platform'), ['source_platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_status_label'), ['status_label'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_updated_at'), ['updated_at'], unique=False)

    op.create_table('ticketevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('from_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('to_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticketevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticketevent_actor'), ['actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticketevent_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticketevent_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticketevent_ticket_id'), ['ticket_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticketevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticketevent_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_ticketevent_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_ticketevent_event_type'))
        batch_op.drop_index(batch_op.f('ix_ticketevent_actor'))

    op.drop_table('ticketevent')
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_updated_at'))
        batch_op.drop_index(batch_op.f('ix_ticket_status_label'))
        batch_op.drop_index(batch_op.f('ix_ticket_source_platform'))
        batch_op.drop_index(batch_op.f('ix_ticket_source_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_project_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_key'))
        batch_op.drop_index(batch_op.f('ix_ticket_created_at'))

    op.drop_table('ticket')
    with op.batch_alter_table('projectrepository', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projectrepository_created_at'))

    op.drop_table('projectrepository')
    with op.batch_alter_table('projectintegration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projectintegration_updated_at'))
        batch_op.drop_index(batch_op.f('ix_projectintegration_provider'))
        batch_op.drop_index(batch_op.f('ix_projectintegration_project_id'))
        batch_op.drop_index(batch_op.f('ix_projectintegration_credential_id'))
        batch_op.drop_index(batch_op.f('ix_projectintegration_created_at'))

    op.drop_table('projectintegration')
    with op.batch_alter_table('chatmessage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatmessage_role'))
        batch_op.drop_index(batch_op.f('ix_chatmessage_created_at'))
        batch_op.drop_index(batch_op.f('ix_chatmessage_chat_thread_id'))

    op.drop_table('chatmessage')
    op.drop_table('analysisreport')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_type'))
        batch_op.drop_index(batch_op.f('ix_activity_timestamp'))
        batch_op.drop_index(batch_op.f('ix_activity_source_platform'))
        batch_op.drop_index(batch_op.f('ix_activity_source_id'))
        batch_op.drop_index(batch_op.f('ix_activity_repository_id'))
        batch_op.drop_index(batch_op.f('ix_activity_author'))

    op.drop_table('activity')
    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repository_url'))

    op.drop_table('repository')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_updated_at'))
        batch_op.drop_index(batch_op.f('ix_project_name'))
        batch_op.drop_index(batch_op.f('ix_project_created_at'))

    op.drop_table('project')
    with op.batch_alter_table('integrationcredential', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrationcredential_updated_at'))
        batch_op.drop_index(batch_op.f('ix_integrationcredential_provider'))
        batch_op.drop_index(batch_op.f('ix_integrationcredential_owner_id'))
        batch_op.drop_index(batch_op.f('ix_integrationcredential_created_at'))

    op.drop_table('integrationcredential')
    with op.batch_alter_table('chatthread', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatthread_updated_at'))
        batch_op.drop_index(batch_op.f('ix_chatthread_owner_id'))
        batch_op.drop_index(batch_op.f('ix_chatthread_external_thread_id'))
        batch_op.drop_index(batch_op.f('ix_chatthread_created_at'))

    op.drop_table('chatthread')
    # ### end Alembic commands ###
